baseURL = 'https://hungryfoolishwork.github.io/'
languageCode = 'en-us'
title = 'Hungry Foolish'
author = "Nathan Borror"
canonifyurls = true
theme = "black-and-light"
publishDir = "docs"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Hungry Foolish"
  disableWebFonts = false